### ISSUE TITLE
Data Format

### ISSUE THREAD

**Issue by tebesu** [wenjiepei/IARN#2]
Hello I am trying to replicate your results could you please tell me what the format for the item/user time series is? Thank you.

**Comment by wenjiepei** [comment]
The item/user time series is a table, each of its elements is a 2-D (d * T) matrix for a time series, here d is the feature dimension of each time step and T is the length of this time series.

**Comment by wenjiepei** [comment]
Thanks for your interest in our work.

The format of the training_time_series.t7 is as follows: 
it contains a data table and a index vector,
  -each of table's elements (entries) is a 2D matrix (d * T) for a time series, here ‘d' is the feature dimension of each time step and ’T' is the length of this time series.
  - the index vector is just the index of the elements in the table, it is consistent with the index in the pairs data ’training_rating.t7’ and ’test_rating.t7’.

I just uploaded a data example (data ‘Clothing’) to the github, you can take a look.

**Comment by tebesu** [comment]
Thank you for your help and quick reply!
